name: My Comment-based Pipeline

on:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contain(github.event.comment.body, '/comment') }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying ..."